[workspace]
authors = ["Justin Bois <bois@caltech.edu>"]
channels = ["conda-forge"]
name = "bebi25"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.1.0"

[dependencies]
python = ">=3.13.5,<3.14"
bokeh = ">=3.7.3,<4"
colorcet = ">=3.1.0,<4"
ipython = ">=9.4.0,<10"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.3,<4"
mypy = ">=1.17.0,<2"
numba = ">=0.61.2,<0.62"
numpy = ">=2.2.6,<3"
openpyxl = ">=3.1.5,<4"
pandas = ">=2.3.1,<3"
pip = ">=25.1.1,<26"
pyarrow = ">=21.0.0,<22"
scipy = ">=1.16.0,<2"
xarray = ">=2025.7.1,<2026"
nodejs = ">=24.4.1,<24.5"
fastexcel = ">=0.14.0,<0.15"
altair = ">=5.5.0,<6"

[pypi-dependencies]
black = ">=25.1.0, <26"
blackcellmagic = ">=0.0.2, <0.0.3"
eqtk = "*"
iqplot = ">=0.3.7, <0.4"
jupyterlab = "*"
jupyter-bokeh = ">=4.0.5, <5"
jupyterlab-spellchecker = ">=0.8.4, <0.9"
marimo = ">=0.14.13, <0.15"
polars = ">=1.31.0, <2"
watermark = ">=2.5.0, <3"
xarray-datatree = ">=0.0.14, <0.0.15"
xarray-einstats = ">=0.9.1, <0.10"

[tool.marimo.formatting]
line_length = 88

[tool.marimo.display]
default_width = "full"

[tool.marimo.runtime]
autorun_on_startup = false
on_cell_change = "lazy"
